# Generated by Django 2.0.7 on 2018-07-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('publish_date', models.DateField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=256)),
                ('license', models.CharField(db_index=True, max_length=265)),
                ('view_count', models.IntegerField(db_index=True)),
                ('likes', models.IntegerField(db_index=True)),
                ('dislikes', models.IntegerField(db_index=True)),
                ('description_text', models.TextField()),
                ('description_html', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Channel')),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.URL')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Search')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Video')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='videos',
            field=models.ManyToManyField(through='youtube.VideoSearch', to='youtube.Video'),
        ),
    ]
